name: 🐛 Bug Report
description: Create a bug report to help us improve ecolog.nvim
title: "Bug: "
labels: ["bug"]
body:
  - type: textarea
    id: describe-the-bug
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: Please provide a clear and concise description about the problem you ran into.
      placeholder: This happened when I ...
  - type: textarea
    id: expected-behavior
    validations:
      required: false
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you would expect to happen."
  - type: textarea
    id: how-to-install
    validations:
      required: true
    attributes:
      label: Installation method
      description: |
        Please share your installation method with us.
      value: |
        Use lazy.nvim:

        ```lua
        {
         'philosofonusus/ecolog.nvim',
          keys = {
            { '<leader>ge', '<cmd>EcologGoto<cr>', desc = 'Go to env file' },
            { '<leader>ec', '<cmd>EcologSnacks<cr>', desc = 'Open a picker' },
            { '<leader>eS', '<cmd>EcologSelect<cr>', desc = 'Switch env file' },
            { '<leader>es', '<cmd>EcologShelterToggle<cr>', desc = 'Ecolog shelter toggle' },
          },
          lazy = false,
          opts = {
            preferred_environment = 'local',
            types = true,
            integrations = {
              lspsaga = true,
              nvim_cmp = true,
              statusline = {
                hidden_mode = true,
              },
              snacks = true,
            },
            shelter = {
              configuration = {
                sources = {
                  ['.env.example'] = 'none',
                },
                partial_mode = {
                  min_mask = 5,
                  show_start = 1,
                  show_end = 1,
                },
                mask_char = '*',
              },
              modules = {
                files = true,
                peek = false,
                snacks_previewer = true,
                snacks = false,
                cmp = true,
              },
            },
            path = vim.fn.getcwd(),
          },
        }
        ```

  - type: textarea
    id: environment-info
    attributes:
      label: Environment
      description: |
        Please share your environment with us, including your neovim version using `nvim -v` and `uname -a`.
      placeholder: |
        neovim version: ...
        distribution (if any): ...
        platform: ...
    validations:
      required: true
